#!/usr/bin/env python3
"""
hugeplc_ascii2.IL から CAL 対象を拾い、llil の fb_family_name と同じ規則で
VAR FUNCTION#ファミリ#インスタンス を1行ずつ出力する。

使用例:
  python emit_function_vars_from_cal.py > function_vars.inc
  # IL 先頭に (* ... *) のあと function_vars.inc の内容を貼る
"""
from __future__ import annotations

import pathlib
import re

CAL_RE = re.compile(r"^\s*CAL\s+(\S+)\s*$", re.I)


def fb_family_name(inst: str) -> str:
    """llil fb_family_name と同じ。"""
    i = inst.rfind("_")
    if i <= 0:
        return inst
    head, tail = inst[:i], inst[i + 1 :]
    if tail and tail.isdigit():
        return head
    return inst


def main() -> None:
    root = pathlib.Path(__file__).resolve().parent
    il_path = root / "hugeplc_ascii2.IL"
    text = il_path.read_text(encoding="utf-8", errors="replace")
    seen: set[str] = set()
    out: list[str] = []
    for line in text.splitlines():
        m = CAL_RE.match(line)
        if not m:
            continue
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        fam = fb_family_name(name)
        out.append(f"VAR FUNCTION#{fam}#{name}")
    out.sort()
    print(f"(* VAR FUNCTION# from CAL: {len(out)} lines, generated by emit_function_vars_from_cal.py *)")
    try:
        for line in out:
            print(line)
    except BrokenPipeError:
        raise SystemExit(0)


def collect_var_lines(il_text: str) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for line in il_text.splitlines():
        m = CAL_RE.match(line)
        if not m:
            continue
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        fam = fb_family_name(name)
        out.append(f"VAR FUNCTION#{fam}#{name}")
    out.sort()
    return out


VAR_PREPEND_MARKER = "(* VAR FUNCTION# from CAL — prepended for rtedge fb_instances / slots_init *)"


def strip_prepended_var_block(text: str) -> str:
    """既に挿入済みの VAR ブロックを除去し、元の IL 本文を返す。"""
    if not text.startswith(VAR_PREPEND_MARKER):
        return text
    # 先頭の命令はプロジェクト固定（再挿入のアンカー）
    anchor = "LD\tatestContact"
    i = text.find(anchor)
    if i == -1:
        return text
    return text[i:]


def prepend_vars_to_il(il_path: pathlib.Path) -> None:
    """IL 先頭に VAR FUNCTION# ブロックを挿入する（上書き）。二重挿入時は置き換え。"""
    text = il_path.read_text(encoding="utf-8", errors="replace")
    text = strip_prepended_var_block(text)
    vars_sorted = collect_var_lines(text)
    header = (
        f"{VAR_PREPEND_MARKER}\n"
        f"(* {len(vars_sorted)} instances *)\n\n"
    )
    body = "\n".join(vars_sorted) + "\n\n"
    il_path.write_text(header + body + text, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--prepend":
        root = pathlib.Path(__file__).resolve().parent
        prepend_vars_to_il(root / "hugeplc_ascii2.IL")
        print("prepended VAR block to hugeplc_ascii2.IL", file=sys.stderr)
    else:
        main()
