#ifndef _PLCPIEC_H_
#define _PLCPIEC_H_

#ifdef  PLCPIEC_EXPORTS
#define PLCPIEC_API __declspec(dllexport)
#else
#define PLCPIEC_API __declspec(dllimport)
#endif

#pragma once

//------------------------------------------------------------------------------
//このファイルはファンクション処理内だけで使用する宣言を記載します。
//------------------------------------------------------------------------------

#include "common.h"

//ファンクション例外コード
#define	FUK_0DIV_ERR			0x0001	// 0除算
#define	FUK_OVERFLOW_ERR		0x0002	// 変数オーバーフロー
#define	FUK_INVALID_VALUE_ERR	0x0003	// 無効値(REAL,LREAL)
#define	FUK_PARAMEFER_ERR		0x0004	// ファンクションパラメーターエラー
#define	FUK_LIMIT_OVER_ERR		0x0005	// 限界値オーバー

// ビット指定用関数
void MaskBitfield(void* any);

// ENO設定用関数
// MOVE
PLCPIEC_API T_BOOL GetMoveEno();
PLCPIEC_API void SetMoveEno(T_BOOL eno);
// ADD
PLCPIEC_API T_BOOL GetAddEno();
PLCPIEC_API void SetAddEno(T_BOOL eno);
//SUB
PLCPIEC_API T_BOOL GetSubEno();
PLCPIEC_API void SetSubEno(T_BOOL eno);
//MUL
PLCPIEC_API T_BOOL GetMulEno();
PLCPIEC_API void SetMulEno(T_BOOL eno);
//DIV
PLCPIEC_API T_BOOL GetDivEno();
PLCPIEC_API void SetDivEno(T_BOOL eno);
//MOD
PLCPIEC_API T_BOOL GetModEno();
PLCPIEC_API void SetModEno(T_BOOL eno);
//NUMERIC
PLCPIEC_API T_BOOL GetNumericEno();
PLCPIEC_API void SetNumericEno(T_BOOL eno);
//EXPT
PLCPIEC_API T_BOOL GetExptEno();
PLCPIEC_API void SetExptEno(T_BOOL eno);
//EQ
PLCPIEC_API T_BOOL GetEqEno();
PLCPIEC_API void SetEqEno(T_BOOL eno);
//GE
PLCPIEC_API T_BOOL GetGeEno();
PLCPIEC_API void SetGeEno(T_BOOL eno);
//GT
PLCPIEC_API T_BOOL GetGtEno();
PLCPIEC_API void SetGtEno(T_BOOL eno);
//LE
PLCPIEC_API T_BOOL GetLeEno();
PLCPIEC_API void SetLeEno(T_BOOL eno);
//LT
PLCPIEC_API T_BOOL GetLtEno();
PLCPIEC_API void SetLtEno(T_BOOL eno);
//NE
PLCPIEC_API T_BOOL GetNeEno();
PLCPIEC_API void SetNeEno(T_BOOL eno);
//STRING_OPE
PLCPIEC_API T_BOOL GetStringOpeEno();
PLCPIEC_API void SetStringOpeEno(T_BOOL eno);
//DWORD_TO
PLCPIEC_API T_BOOL GetDWordToEno();
PLCPIEC_API void SetDWordToEno(T_BOOL eno);
//DINT_TO
PLCPIEC_API T_BOOL GetDIntToEno();
PLCPIEC_API void SetDIntToEno(T_BOOL eno);
//LINT_TO
PLCPIEC_API T_BOOL GetLIntToEno();
PLCPIEC_API void SetLIntToEno(T_BOOL eno);
//REAL_TO
PLCPIEC_API T_BOOL GetRealToEno();
PLCPIEC_API void SetRealToEno(T_BOOL eno);
//LREAL_TO
PLCPIEC_API T_BOOL GetLRealToEno();
PLCPIEC_API void SetLRealToEno(T_BOOL eno);
//BCD_TO
PLCPIEC_API T_BOOL GetBcdToEno();
PLCPIEC_API void SetBcdToEno(T_BOOL eno);
//SELECT
PLCPIEC_API T_BOOL GetSelectEno();
PLCPIEC_API void SetSelectEno(T_BOOL eno);
//NEG
PLCPIEC_API T_BOOL GetNegEno();
PLCPIEC_API void SetNegEno(T_BOOL eno);
//TRUNC
PLCPIEC_API T_BOOL GetTruncEno();
PLCPIEC_API void SetTruncEno(T_BOOL eno);

//-----------------------------
//共通処理
//-----------------------------
extern T_BOOL IsDetailMode();	// 

//例外処理
extern void Eexception_Post(int ExceptCode, char *Hint);

// REAL型の値が無効か確認
extern int ChckREAL(T_REAL IN1);

// LREAL型の値が無効か確認
extern int ChckLREAL(T_LREAL IN1);

// 加算のオーバーフローを検出
//extern int ADD_Overflow_REAL(T_REAL a, T_REAL b);
//extern int ADD_Overflow_LREAL(T_LREAL a, T_LREAL b);
extern int ADD_Overflow_SINT(T_SINT a, T_SINT b);
extern int ADD_Overflow_DINT(T_DINT a, T_DINT b);
extern int ADD_Overflow_INT(T_INT a, T_INT b);
extern int ADD_Overflow_LINT(T_LINT a, T_LINT b);
extern int ADD_Overflow_UDINT(T_UDINT a, T_UDINT b);
extern int ADD_Overflow_UINT(T_UINT a, T_UINT b);
extern int ADD_Overflow_USINT(T_USINT a, T_USINT b);
extern int ADD_Overflow_ULINT(T_ULINT a, T_ULINT b);
extern int ADD_Overflow_TIME(T_TIME a, T_TIME b);
// 減算のオーバーフローを検出
extern int SUB_Overflow_SINT (T_SINT  a, T_SINT  b);
extern int SUB_Overflow_DINT (T_DINT  a, T_DINT  b);
extern int SUB_Overflow_INT  (T_INT   a, T_INT   b);
extern int SUB_Overflow_LINT (T_LINT  a, T_LINT  b);
extern int SUB_Overflow_UDINT(T_UDINT a, T_UDINT b);
extern int SUB_Overflow_UINT (T_UINT  a, T_UINT  b);
extern int SUB_Overflow_USINT(T_USINT a, T_USINT b);
extern int SUB_Overflow_ULINT(T_ULINT a, T_ULINT b);
extern int SUB_Overflow_TIME (T_TIME  a, T_TIME  b);
// 乗算のオーバーフローを検出
extern int MUL_Overflow_SINT (T_SINT  a, T_SINT  b);
extern int MUL_Overflow_DINT (T_DINT  a, T_DINT  b);
extern int MUL_Overflow_INT  (T_INT   a, T_INT   b);
extern int MUL_Overflow_LINT (T_LINT  a, T_LINT  b);
extern int MUL_Overflow_UDINT(T_UDINT a, T_UDINT b);
extern int MUL_Overflow_UINT (T_UINT  a, T_UINT  b);
extern int MUL_Overflow_USINT(T_USINT a, T_USINT b);
extern int MUL_Overflow_ULINT(T_ULINT a, T_ULINT b);
extern int MUL_Overflow_TIME (T_TIME  a, T_TIME  b);
extern int MUL_Overflow_TIME_UDINT(T_TIME a, T_UDINT b);
// 除算のオーバーフローを検出
extern int DIV_Overflow_SINT(T_SINT  a, T_SINT  b);
extern int DIV_Overflow_DINT(T_DINT  a, T_DINT  b);
extern int DIV_Overflow_INT (T_INT   a, T_INT   b);
extern int DIV_Overflow_LINT(T_LINT  a, T_LINT  b);

//-----------------------------
//比較ファンクション
//-----------------------------

//EQ(比較 : ==  )
PLCPIEC_API P_ANY EQ			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EQ_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//GE(比較 : >= )
PLCPIEC_API P_ANY GE			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GE_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//GT(比較 : >  )
PLCPIEC_API P_ANY GT			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GT_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//LE(比較 : <= )
PLCPIEC_API P_ANY LE			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LE_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//LT(比較 : <  )
PLCPIEC_API P_ANY LT			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LT_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//NE(比較 : <> )
PLCPIEC_API P_ANY NE			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NE_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//-----------------------------
//算術
//-----------------------------

//ADD	(ANY_NUM 型の加算)
PLCPIEC_API P_ANY	ADD			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	ADD_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//ADD_T_T  (TIME 型の加算)
PLCPIEC_API P_ANY ADD_T_T(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//DIV  (ANY_NUM 型の除算)
PLCPIEC_API P_ANY	DIV			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	DIV_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//DIV_T_AN	(TIMEの除算)
PLCPIEC_API P_ANY DIV_T_AN		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AN_ULINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//DIV_T_AI	(TIMEの除算)
PLCPIEC_API P_ANY DIV_T_AI		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DIV_T_AI_ULINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//DIV_T_R	(TIMEの除算)
PLCPIEC_API P_ANY DIV_T_R(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//EXPT  (べき乗)
PLCPIEC_API P_ANY EXPT				(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_REAL_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXPT_LREAL_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MOD  (剰余算)
PLCPIEC_API P_ANY	MOD			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOD_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MOVE  (転送)
PLCPIEC_API P_ANY	MOVE		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_TIME	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_DWORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_WORD	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_BYTE	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_BOOL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MOVE_STRING	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MUL ( ANY_NUM 型の乗算)
PLCPIEC_API P_ANY	MUL			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	MUL_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MUL_T_AN (TIME 型の乗算)
PLCPIEC_API P_ANY MUL_T_AN		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_REAL  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_LREAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AN_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MUL_T_AI (TIME 型の乗算)
PLCPIEC_API P_ANY MUL_T_AI		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_INT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MUL_T_AI_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//MUL_T_R  (TIME 型の乗算)
PLCPIEC_API P_ANY MUL_T_R(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//NEG  (2 の補数)
PLCPIEC_API P_ANY	NEG			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	NEG_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//SUB  (ANY_NUM 型の減算)
PLCPIEC_API P_ANY	SUB			(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_REAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_LREAL	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_SINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_DINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_INT		(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_LINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_UDINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_UINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_USINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY	SUB_ULINT	(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);

//SUB_T_T  (TIME 型の減算)
PLCPIEC_API P_ANY SUB_T_T(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);


//-----------------------------
//型変換ファンクション
//-----------------------------

// BYTE型からの変換
PLCPIEC_API P_ANY BYTE_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BYTE_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// BOOL型からの変換
PLCPIEC_API P_ANY BOOL_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BOOL_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// INT型からの変換
PLCPIEC_API P_ANY INT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_B_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_D_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_W_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// BCD型から変換
PLCPIEC_API P_ANY B_BCD_TO_DINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY B_BCD_TO_INT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY B_BCD_TO_LINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY B_BCD_TO_SINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY BCD_TO_DINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY D_BCD_TO_DINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY D_BCD_TO_INT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY D_BCD_TO_LINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY D_BCD_TO_SINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY W_BCD_TO_DINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY W_BCD_TO_INT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY W_BCD_TO_LINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY W_BCD_TO_SINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//DINT型から変換
PLCPIEC_API P_ANY DINT_TO_B_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_BCD  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_D_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_TIME (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_W_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//LREAL型から変換
PLCPIEC_API P_ANY LREAL_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//REAL型から変換
PLCPIEC_API P_ANY REAL_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//DWORD型から変換
PLCPIEC_API P_ANY DWORD_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// LINT型からの変換
PLCPIEC_API P_ANY LINT_TO_B_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_D_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_W_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// SINT型からの変換
PLCPIEC_API P_ANY SINT_TO_B_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_D_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_W_BCD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// UDINT型からの変換
PLCPIEC_API P_ANY UDINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// UINT型からの変換
PLCPIEC_API P_ANY UINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// USINT型からの変換
PLCPIEC_API P_ANY USINT_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// WORD型からの変換
PLCPIEC_API P_ANY WORD_TO_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 小数点以下切り捨て
PLCPIEC_API P_ANY TRUNC_SINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TRUNC_INT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TRUNC_DINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TRUNC_LINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// TIME型から変換
PLCPIEC_API P_ANY TIME_TO_DINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
/// <summary>
/// ビットローテーション関連 RotShift.c
/// </summary>
PLCPIEC_API P_ANY ROL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROL_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROL_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROL_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROR_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROR_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ROR_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHL_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHL_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHL_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHR_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHR_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SHR_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SIZEOF(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LOWER_BOUND(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//-----------------------------
//論理演算ファンクション LogicOpe.c
//-----------------------------
// AND
PLCPIEC_API P_ANY AND(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY AND_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY AND_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY AND_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY AND_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// ANDN
PLCPIEC_API P_ANY ANDN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ANDN_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ANDN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ANDN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ANDN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// NOT
PLCPIEC_API P_ANY NOT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NOT_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NOT_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NOT_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY NOT_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// OR
PLCPIEC_API P_ANY OR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY OR_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY OR_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY OR_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY OR_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// ORN
PLCPIEC_API P_ANY ORN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ORN_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ORN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ORN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ORN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// XOR
PLCPIEC_API P_ANY XOR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XOR_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XOR_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XOR_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XOR_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// XORN
PLCPIEC_API P_ANY XORN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XORN_BOOL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XORN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XORN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY XORN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//-----------------------------
//ビット操作ファンクション BitOpe.c
//-----------------------------
PLCPIEC_API P_ANY BIT_TEST(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GET_CHAR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GET_LSB (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY GET_MSB (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SET_LSB (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SET_MSB (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SWAP    (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY PARITY  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY PARITY_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY PARITY_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY PARITY_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY I_BIT_IN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY I_BIT_IN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY I_BIT_IN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY I_BIT_IN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY R_BIT_IN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY R_BIT_IN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY R_BIT_IN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY R_BIT_IN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY S_BIT_IN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY S_BIT_IN_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY S_BIT_IN_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY S_BIT_IN_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_BUFFER(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//-----------------------------
//数値ファンクション Numeric.c
//-----------------------------
// 絶対値
PLCPIEC_API P_ANY ABS(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_ULINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ABS_TIME (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 逆余弦
PLCPIEC_API P_ANY ACOS(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ACOS_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ACOS_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 逆正弦
PLCPIEC_API P_ANY ASIN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ASIN_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ASIN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 逆正接
PLCPIEC_API P_ANY ATAN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ATAN_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY ATAN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 余弦
PLCPIEC_API P_ANY COS(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY COS_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY COS_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 正弦
PLCPIEC_API P_ANY SIN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SIN_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SIN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 正接
PLCPIEC_API P_ANY TAN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TAN_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TAN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 指数関数
PLCPIEC_API P_ANY EXP(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXP_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY EXP_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 自然対数
PLCPIEC_API P_ANY LN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LN_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 常用対数
PLCPIEC_API P_ANY LOG(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LOG_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LOG_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 平方根
PLCPIEC_API P_ANY SQRT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SQRT_REAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SQRT_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//-----------------------------
//文字列ファンクション StringOpe.c
//-----------------------------
// 文字列化
PLCPIEC_API P_ANY BYTE_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY WORD_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DWORD_TO_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SINT_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY INT_TO_STRING  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY DINT_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LINT_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY USINT_TO_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UINT_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY UDINT_TO_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY TIME_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY REAL_TO_STRING (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LREAL_TO_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 数値化
PLCPIEC_API P_ANY STRING_TO_BYTE (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_WORD (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_TIME (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY STRING_TO_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 結合
PLCPIEC_API P_ANY CONCAT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 削除
PLCPIEC_API P_ANY DELETE_STR(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 検索
PLCPIEC_API P_ANY FIND(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 挿入
PLCPIEC_API P_ANY INSERT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 文字列長取得
PLCPIEC_API P_ANY LEN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// 置換
PLCPIEC_API P_ANY REPLACE(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
// コピー
PLCPIEC_API P_ANY LEFT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);		// 左から
PLCPIEC_API P_ANY MID(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);		// 中央
PLCPIEC_API P_ANY RIGHT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);		// 右から
// 比較
PLCPIEC_API P_ANY EQ_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// イコール
PLCPIEC_API P_ANY NE_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// ノットイコール
PLCPIEC_API P_ANY GE_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// 大なりイコール
PLCPIEC_API P_ANY GT_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// 大なり
PLCPIEC_API P_ANY LE_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// 小なりイコール
PLCPIEC_API P_ANY LT_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);	// 小なり
//-----------------------------
//選択ファンクション Select.c
//-----------------------------
//範囲判定
PLCPIEC_API P_ANY LIMIT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_SINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_INT   (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_DINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_LINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_REAL  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_LREAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY LIMIT_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//最大値判定
PLCPIEC_API P_ANY MAX(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_ULINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MAX_STR  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//最小値判定
PLCPIEC_API P_ANY MIN(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_SINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_INT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_DINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_LINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_USINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_UINT (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_UDINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_ULINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_REAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_LREAL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY MIN_STR  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
//返却値選択
PLCPIEC_API P_ANY SEL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_SINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_INT   (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_DINT  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_REAL  (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_LREAL (P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_STRING(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_LINT(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_TIME(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_WORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_DWORD(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_BOOL(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
PLCPIEC_API P_ANY SEL_BYTE(P_ANY a1, P_ANY a2, P_ANY a3, P_ANY a4);
#endif